# docker-compose up //
version: '3.3'

services:
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    hostname: pushgateway
    ports:
      - '9091:9091'
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - pushgateway
    links:
      - pushgateway:pushgateway
  grafana:
    container_name: grafana
    image: grafana/grafana
    hostname: grafana
    ports:
      - '3000:3000'
    links:
      - prometheus:prometheus
  interlok: 
    image: adaptrislabs/interlok-docker-prometheus
    container_name: interlok-profiler
    hostname: interlok
    ports:
      - '8080:8080'
      - '5555:5555'
    environment:
      JVM_ARGS: -javaagent:lib/aspectjweaver.jar -Dorg.aspectj.weaver.loadtime.configuration=META-INF/profiler-aop.xml
    links:
      - pushgateway:pushgateway
